const data = [
  {'city': 'Abbeville', 'state': 'Louisiana'},
  {'city': 'Aberdeen', 'state': 'Maryland'},
  {'city': 'Aberdeen', 'state': 'Mississippi'},
  {'city': 'Aberdeen', 'state': 'South Dakota'},
  {'city': 'Aberdeen', 'state': 'Washington'},
  {'city': 'Abilene', 'state': 'Texas'},
  {'city': 'Abilene', 'state': 'Kansas'},
  {'city': 'Abingdon', 'state': 'Virginia'},
  {'city': 'Abington', 'state': 'Massachusetts'},
  {'city': 'Absecon', 'state': 'New Jersey'},
  {'city': 'Accokeek', 'state': 'Maryland'},
  {'city': 'Acton', 'state': 'Massachusetts'},
  {'city': 'Acushnet', 'state': 'Massachusetts'},
  {'city': 'Acworth', 'state': 'Georgia'},
  {'city': 'Ada', 'state': 'Oklahoma'},
  {'city': 'Adams', 'state': 'Massachusetts'},
  {'city': 'Addison', 'state': 'Illinois'},
  {'city': 'Addison', 'state': 'Texas'},
  {'city': 'Adelanto', 'state': 'California'},
  {'city': 'Adelphi', 'state': 'Maryland'},
  {'city': 'Adrian', 'state': 'Michigan'},
  {'city': 'Affton', 'state': 'Missouri'},
  {'city': 'Agawam', 'state': 'Massachusetts'},
  {'city': 'Agoura Hills', 'state': 'California'},
  {'city': 'Ahuimanu', 'state': 'Hawaii'},
  {'city': 'Aiea', 'state': 'Hawaii'},
  {'city': 'Aiken', 'state': 'South Carolina'},
  {'city': 'Air Force Academy', 'state': 'Colorado'},
  {'city': 'Airmont', 'state': 'New York'},
  {'city': 'Akron', 'state': 'Ohio'},
  {'city': 'Alabaster', 'state': 'Alabama'},
  {'city': 'Alachua', 'state': 'Florida'},
  {'city': 'Alameda', 'state': 'California'},
  {'city': 'Alamo', 'state': 'California'},
  {'city': 'Alamo', 'state': 'Texas'},
  {'city': 'Alamo Heights', 'state': 'Texas'},
  {'city': 'Alamogordo', 'state': 'New Mexico'},
  {'city': 'Alamosa', 'state': 'Colorado'},
  {'city': 'Albany', 'state': 'Georgia'},
  {'city': 'Albany', 'state': 'California'},
  {'city': 'Albany', 'state': 'New York'},
  {'city': 'Albany', 'state': 'Oregon'},
  {'city': 'Albemarle', 'state': 'North Carolina'},
  {'city': 'Albert Lea', 'state': 'Minnesota'},
  {'city': 'Albertville', 'state': 'Alabama'},
  {'city': 'Albion', 'state': 'Michigan'},
  {'city': 'Albion', 'state': 'New York'},
  {'city': 'Albuquerque', 'state': 'New Mexico'},
  {'city': 'Alcoa', 'state': 'Tennessee'},
  {'city': 'Alden', 'state': 'New York'},
  {'city': 'Alderwood Manor', 'state': 'Washington'},
  {'city': 'Aldine', 'state': 'Texas'},
  {'city': 'Alexander City', 'state': 'Alabama'},
  {'city': 'Alexandria', 'state': 'Indiana'},
  {'city': 'Alexandria', 'state': 'Minnesota'},
  {'city': 'Alexandria', 'state': 'Kentucky'},
  {'city': 'Alexandria', 'state': 'Louisiana'},
  {'city': 'Alexandria', 'state': 'Virginia'},
  {'city': 'Algonquin', 'state': 'Illinois'},
  {'city': 'Alhambra', 'state': 'California'},
  {'city': 'Alice', 'state': 'Texas'},
  {'city': 'Aliquippa', 'state': 'Pennsylvania'},
  {'city': 'Aliso Viejo', 'state': 'California'},
  {'city': 'Allegany', 'state': 'New York'},
  {'city': 'Allen', 'state': 'Texas'},
  {'city': 'Allen Park', 'state': 'Michigan'},
  {'city': 'Allendale', 'state': 'Michigan'},
  {'city': 'Allendale', 'state': 'New Jersey'},
  {'city': 'Allentown', 'state': 'Pennsylvania'},
  {'city': 'Alliance', 'state': 'Ohio'},
  {'city': 'Alliance', 'state': 'Nebraska'},
  {'city': 'Allouez', 'state': 'Wisconsin'},
  {'city': 'Alma', 'state': 'Michigan'},
  {'city': 'Aloha', 'state': 'Oregon'},
  {'city': 'Alondra Park', 'state': 'California'},
  {'city': 'Alpena', 'state': 'Michigan'},
  {'city': 'Alpharetta', 'state': 'Georgia'},
  {'city': 'Alpine', 'state': 'California'},
  {'city': 'Alpine', 'state': 'Utah'},
  {'city': 'Alsip', 'state': 'Illinois'},
  {'city': 'Alta Sierra', 'state': 'California'},
  {'city': 'Altadena', 'state': 'California'},
  {'city': 'Altamont', 'state': 'Oregon'},
  {'city': 'Altamont', 'state': 'New York'},
  {'city': 'Altamonte Springs', 'state': 'Florida'},
  {'city': 'Alton', 'state': 'Illinois'},
  {'city': 'Altoona', 'state': 'Iowa'},
  {'city': 'Altoona', 'state': 'Pennsylvania'},
  {'city': 'Altoona', 'state': 'Wisconsin'},
  {'city': 'Altus', 'state': 'Oklahoma'},
  {'city': 'Alum Rock', 'state': 'California'},
  {'city': 'Alvin', 'state': 'Texas'},
  {'city': 'Amarillo', 'state': 'Texas'},
  {'city': 'Ambler', 'state': 'Pennsylvania'},
  {'city': 'Ambridge', 'state': 'Pennsylvania'},
  {'city': 'American Canyon', 'state': 'California'},
  {'city': 'American Fork', 'state': 'Utah'},
  {'city': 'Americus', 'state': 'Georgia'},
  {'city': 'Ames', 'state': 'Iowa'},
  {'city': 'Amesbury', 'state': 'Massachusetts'},
  {'city': 'Amherst', 'state': 'New Hampshire'},
  {'city': 'Amherst', 'state': 'Massachusetts'},
  {'city': 'Amherst', 'state': 'Ohio'},
  {'city': 'Amherst', 'state': 'New York'},
  {'city': 'Amherst Center', 'state': 'Massachusetts'},
  {'city': 'Amityville', 'state': 'New York'},
  {'city': 'Ammon', 'state': 'Idaho'},
  {'city': 'Amory', 'state': 'Mississippi'},
  {'city': 'Amsterdam', 'state': 'New York'},
  {'city': 'Anaconda-Deer Lodge County', 'state': 'Montana'},
  {'city': 'Anacortes', 'state': 'Washington'},
  {'city': 'Anadarko', 'state': 'Oklahoma'},
  {'city': 'Anaheim', 'state': 'California'},
  {'city': 'Anchorage', 'state': 'Alaska'},
  {'city': 'Andalusia', 'state': 'Alabama'},
  {'city': 'Anderson', 'state': 'California'},
  {'city': 'Anderson', 'state': 'Indiana'},
  {'city': 'Anderson', 'state': 'South Carolina'},
  {'city': 'Anderson Mill', 'state': 'Texas'},
  {'city': 'Andover', 'state': 'Florida'},
  {'city': 'Andover', 'state': 'Minnesota'},
  {'city': 'Andover', 'state': 'Massachusetts'},
  {'city': 'Andover', 'state': 'Kansas'},
  {'city': 'Andrews', 'state': 'Texas'},
  {'city': 'Andrews AFB', 'state': 'Maryland'},
  {'city': 'Angleton', 'state': 'Texas'},
  {'city': 'Angola', 'state': 'Indiana'},
  {'city': 'Ankeny', 'state': 'Iowa'},
  {'city': 'Ann Arbor', 'state': 'Michigan'},
  {'city': 'Annandale', 'state': 'Virginia'},
  {'city': 'Annapolis', 'state': 'Maryland'},
  {'city': 'Anniston', 'state': 'Alabama'},
  {'city': 'Anoka', 'state': 'Minnesota'},
  {'city': 'Ansonia', 'state': 'Connecticut'},
  {'city': 'Anthony', 'state': 'New Mexico'},
  {'city': 'Antigo', 'state': 'Wisconsin'},
  {'city': 'Antioch', 'state': 'Illinois'},
  {'city': 'Antioch', 'state': 'California'},
  {'city': 'Apache Junction', 'state': 'Arizona'},
  {'city': 'Apex', 'state': 'North Carolina'},
  {'city': 'Apollo Beach', 'state': 'Florida'},
  {'city': 'Apopka', 'state': 'Florida'},
  {'city': 'Apple Valley', 'state': 'California'},
  {'city': 'Apple Valley', 'state': 'Minnesota'},
  {'city': 'Appleton', 'state': 'Wisconsin'},
  {'city': 'Applewood', 'state': 'Colorado'},
  {'city': 'Aptos', 'state': 'California'},
  {'city': 'Aquia Harbour', 'state': 'Virginia'},
  {'city': 'Arab', 'state': 'Alabama'},
  {'city': 'Arabi', 'state': 'Louisiana'},
  {'city': 'Aransas Pass', 'state': 'Texas'},
  {'city': 'Arbutus', 'state': 'Maryland'},
  {'city': 'Arcadia', 'state': 'California'},
  {'city': 'Arcadia', 'state': 'Florida'},
  {'city': 'Arcadia', 'state': 'New York'},
  {'city': 'Arcata', 'state': 'California'},
  {'city': 'Archbald', 'state': 'Pennsylvania'},
  {'city': 'Archdale', 'state': 'North Carolina'},
  {'city': 'Arden Hills', 'state': 'Minnesota'},
  {'city': 'Arden-Arcade', 'state': 'California'},
  {'city': 'Ardmore', 'state': 'Oklahoma'},
  {'city': 'Ardmore', 'state': 'Pennsylvania'},
  {'city': 'Arkadelphia', 'state': 'Arkansas'},
  {'city': 'Arkansas City', 'state': 'Kansas'},
  {'city': 'Arlington', 'state': 'Massachusetts'},
  {'city': 'Arlington', 'state': 'Texas'},
  {'city': 'Arlington', 'state': 'New York'},
  {'city': 'Arlington', 'state': 'Virginia'},
  {'city': 'Arlington', 'state': 'Washington'},
  {'city': 'Arlington Heights', 'state': 'Illinois'},
  {'city': 'Arnold', 'state': 'Missouri'},
  {'city': 'Arnold', 'state': 'Maryland'},
  {'city': 'Arroyo Grande', 'state': 'California'},
  {'city': 'Artesia', 'state': 'California'},
  {'city': 'Artesia', 'state': 'New Mexico'},
  {'city': 'Artondale', 'state': 'Washington'},
  {'city': 'Arvada', 'state': 'Colorado'},
  {'city': 'Arvin', 'state': 'California'},
  {'city': 'Asbury Park', 'state': 'New Jersey'},
  {'city': 'Asheboro', 'state': 'North Carolina'},
  {'city': 'Asheville', 'state': 'North Carolina'},
  {'city': 'Ashland', 'state': 'Oregon'},
  {'city': 'Ashland', 'state': 'Ohio'},
  {'city': 'Ashland', 'state': 'Virginia'},
  {'city': 'Ashland', 'state': 'Wisconsin'},
  {'city': 'Ashland', 'state': 'New Jersey'},
  {'city': 'Ashland', 'state': 'Massachusetts'},
  {'city': 'Ashland', 'state': 'Kentucky'},
  {'city': 'Ashland', 'state': 'California'},
  {'city': 'Ashtabula', 'state': 'Ohio'},
  {'city': 'Ashwaubenon', 'state': 'Wisconsin'},
  {'city': 'Aspen Hill', 'state': 'Maryland'},
  {'city': 'Astoria', 'state': 'Oregon'},
  {'city': 'Atascadero', 'state': 'California'},
  {'city': 'Atascocita', 'state': 'Texas'},
  {'city': 'Atchison', 'state': 'Kansas'},
  {'city': 'Athens', 'state': 'Alabama'},
  {'city': 'Athens', 'state': 'Texas'},
  {'city': 'Athens', 'state': 'Tennessee'},
  {'city': 'Athens', 'state': 'Ohio'},
  {'city': 'Athens-Clarke County', 'state': 'Georgia'},
  {'city': 'Atherton', 'state': 'California'},
  {'city': 'Athol', 'state': 'Massachusetts'},
  {'city': 'Atkinson', 'state': 'New Hampshire'},
  {'city': 'Atlanta', 'state': 'Georgia'},
  {'city': 'Atlantic', 'state': 'Iowa'},
  {'city': 'Atlantic Beach', 'state': 'Florida'},
  {'city': 'Atlantic City', 'state': 'New Jersey'},
  {'city': 'Atmore', 'state': 'Alabama'},
  {'city': 'Attalla', 'state': 'Alabama'},
  {'city': 'Attica', 'state': 'New York'},
  {'city': 'Attleboro', 'state': 'Massachusetts'},
  {'city': 'Atwater', 'state': 'California'},
  {'city': 'Auburn', 'state': 'California'},
  {'city': 'Auburn', 'state': 'Alabama'},
  {'city': 'Auburn', 'state': 'Georgia'},
  {'city': 'Auburn', 'state': 'Indiana'},
  {'city': 'Auburn', 'state': 'Massachusetts'},
  {'city': 'Auburn', 'state': 'Maine'},
  {'city': 'Auburn', 'state': 'New York'},
  {'city': 'Auburn', 'state': 'Washington'},
  {'city': 'Auburn Hills', 'state': 'Michigan'},
  {'city': 'Auburndale', 'state': 'Florida'},
  {'city': 'Audubon', 'state': 'New Jersey'},
  {'city': 'Audubon', 'state': 'Pennsylvania'},
  {'city': 'August', 'state': 'California'},
  {'city': 'Augusta', 'state': 'Maine'},
  {'city': 'Augusta', 'state': 'Kansas'},
  {'city': 'Augusta-Richmond County', 'state': 'Georgia'},
  {'city': 'Aurora', 'state': 'Illinois'},
  {'city': 'Aurora', 'state': 'Colorado'},
  {'city': 'Aurora', 'state': 'Missouri'},
  {'city': 'Aurora', 'state': 'New York'},
  {'city': 'Aurora', 'state': 'Ohio'},
  {'city': 'Austin', 'state': 'Texas'},
  {'city': 'Austin', 'state': 'Minnesota'},
  {'city': 'Austintown', 'state': 'Ohio'},
  {'city': 'Avenal', 'state': 'California'},
  {'city': 'Avenel', 'state': 'New Jersey'},
  {'city': 'Aventura', 'state': 'Florida'},
  {'city': 'Avocado Heights', 'state': 'California'},
  {'city': 'Avon', 'state': 'Connecticut'},
  {'city': 'Avon', 'state': 'Indiana'},
  {'city': 'Avon', 'state': 'Ohio'},
  {'city': 'Avon', 'state': 'New York'},
  {'city': 'Avon Lake', 'state': 'Ohio'},
  {'city': 'Avon Park', 'state': 'Florida'},
  {'city': 'Avondale', 'state': 'Arizona'},
  {'city': 'Ayer', 'state': 'Massachusetts'},
  {'city': 'Azalea Park', 'state': 'Florida'},
  {'city': 'Azle', 'state': 'Texas'},
  {'city': 'Aztec', 'state': 'New Mexico'},
  {'city': 'Azusa', 'state': 'California'},
  {'city': 'Babylon', 'state': 'New York'},
  {'city': 'Back Mountain', 'state': 'Pennsylvania'},
  {'city': 'Bacliff', 'state': 'Texas'},
  {'city': 'Bailey’s Crossroads', 'state': 'Virginia'},
  {'city': 'Bainbridge', 'state': 'Georgia'},
  {'city': 'Bainbridge Island', 'state': 'Washington'},
  {'city': 'Baker', 'state': 'Louisiana'},
  {'city': 'Baker City', 'state': 'Oregon'},
  {'city': 'Bakersfield', 'state': 'California'},
  {'city': 'Balch Springs', 'state': 'Texas'},
  {'city': 'Baldwin', 'state': 'Pennsylvania'},
  {'city': 'Baldwin', 'state': 'New York'},
  {'city': 'Baldwin Harbor', 'state': 'New York'},
  {'city': 'Baldwin Park', 'state': 'California'},
  {'city': 'Baldwinsville', 'state': 'New York'},
  {'city': 'Ballenger Creek', 'state': 'Maryland'},
  {'city': 'Ballston', 'state': 'New York'},
  {'city': 'Ballwin', 'state': 'Missouri'},
  {'city': 'Baltimore', 'state': 'Maryland'},
  {'city': 'Bangor', 'state': 'Maine'},
  {'city': 'Bangor Trident Base', 'state': 'Washington'},
  {'city': 'Banning', 'state': 'California'},
  {'city': 'Baraboo', 'state': 'Wisconsin'},
  {'city': 'Barberton', 'state': 'Ohio'},
  {'city': 'Barclay-Kingston', 'state': 'New Jersey'},
  {'city': 'Bardstown', 'state': 'Kentucky'},
  {'city': 'Barnhart', 'state': 'Missouri'},
  {'city': 'Barnstable Town', 'state': 'Massachusetts'},
  {'city': 'Barre', 'state': 'Vermont'},
  {'city': 'Barrington', 'state': 'Rhode Island'},
  {'city': 'Barrington', 'state': 'New Jersey'},
  {'city': 'Barrington', 'state': 'New Hampshire'},
  {'city': 'Barrington', 'state': 'Illinois'},
  {'city': 'Barstow', 'state': 'California'},
  {'city': 'Bartlesville', 'state': 'Oklahoma'},
  {'city': 'Bartlett', 'state': 'Illinois'},
  {'city': 'Bartlett', 'state': 'Tennessee'},
  {'city': 'Barton', 'state': 'New York'},
  {'city': 'Bartonville', 'state': 'Illinois'},
  {'city': 'Bartow', 'state': 'Florida'},
  {'city': 'Bastrop', 'state': 'Louisiana'},
  {'city': 'Batavia', 'state': 'Illinois'},
  {'city': 'Batavia', 'state': 'New York'},
  {'city': 'Batesville', 'state': 'Mississippi'},
  {'city': 'Batesville', 'state': 'Indiana'},
  {'city': 'Batesville', 'state': 'Arkansas'},
  {'city': 'Bath', 'state': 'Maine'},
  {'city': 'Bath', 'state': 'New York'},
  {'city': 'Baton Rouge', 'state': 'Louisiana'},
  {'city': 'Battle Creek', 'state': 'Michigan'},
  {'city': 'Battle Ground', 'state': 'Washington'},
  {'city': 'Bay City', 'state': 'Texas'},
  {'city': 'Bay City', 'state': 'Michigan'},
  {'city': 'Bay Minette', 'state': 'Alabama'},
  {'city': 'Bay Point', 'state': 'California'},
  {'city': 'Bay Shore', 'state': 'New York'},
  {'city': 'Bay St. Louis', 'state': 'Mississippi'},
  {'city': 'Bay Village', 'state': 'Ohio'},
  {'city': 'Bayonet Point', 'state': 'Florida'},
  {'city': 'Bayonne', 'state': 'New Jersey'},
  {'city': 'Bayou Cane', 'state': 'Louisiana'},
  {'city': 'Bayport', 'state': 'New York'},
  {'city': 'Bayshore Gardens', 'state': 'Florida'},
  {'city': 'Baytown', 'state': 'Texas'},
  {'city': 'Bayville', 'state': 'New York'},
  {'city': 'Baywood', 'state': 'New York'},
  {'city': 'Baywood-Los Osos', 'state': 'California'},
  {'city': 'Beach Park', 'state': 'Illinois'},
  {'city': 'Beachwood', 'state': 'Ohio'},
  {'city': 'Beachwood', 'state': 'New Jersey'},
  {'city': 'Beacon', 'state': 'New York'},
  {'city': 'Beacon Square', 'state': 'Florida'},
  {'city': 'Bear', 'state': 'Delaware'},
  {'city': 'Beatrice', 'state': 'Nebraska'},
  {'city': 'Beaufort', 'state': 'South Carolina'},
  {'city': 'Beaumont', 'state': 'Texas'},
  {'city': 'Beaumont', 'state': 'California'},
  {'city': 'Beaver Dam', 'state': 'Wisconsin'},
  {'city': 'Beaver Falls', 'state': 'Pennsylvania'},
  {'city': 'Beavercreek', 'state': 'Ohio'},
  {'city': 'Beaverton', 'state': 'Oregon'},
  {'city': 'Beckett Ridge', 'state': 'Ohio'},
  {'city': 'Beckley', 'state': 'West Virginia'},
  {'city': 'Bedford', 'state': 'Virginia'},
  {'city': 'Bedford', 'state': 'Texas'},
  {'city': 'Bedford', 'state': 'Ohio'},
  {'city': 'Bedford', 'state': 'New York'},
  {'city': 'Bedford', 'state': 'New Hampshire'},
  {'city': 'Bedford', 'state': 'Massachusetts'},
  {'city': 'Bedford', 'state': 'Indiana'},
  {'city': 'Bedford Heights', 'state': 'Ohio'},
  {'city': 'Bee Ridge', 'state': 'Florida'},
  {'city': 'Beech Grove', 'state': 'Indiana'},
  {'city': 'Beecher', 'state': 'Michigan'},
  {'city': 'Beekman', 'state': 'New York'},
  {'city': 'Beeville', 'state': 'Texas'},
  {'city': 'Bel Air', 'state': 'Maryland'},
  {'city': 'Bel Air North', 'state': 'Maryland'},
  {'city': 'Bel Air South', 'state': 'Maryland'},
  {'city': 'Belchertown', 'state': 'Massachusetts'},
  {'city': 'Belen', 'state': 'New Mexico'},
  {'city': 'Belfast', 'state': 'Maine'},
  {'city': 'Bell', 'state': 'California'},
  {'city': 'Bell Gardens', 'state': 'California'},
  {'city': 'Bella Vista', 'state': 'Arkansas'},
  {'city': 'Bellair-Meadowbrook Terrace', 'state': 'Florida'},
  {'city': 'Bellaire', 'state': 'Texas'},
  {'city': 'Bellbrook', 'state': 'Ohio'},
  {'city': 'Belle Chasse', 'state': 'Louisiana'},
  {'city': 'Belle Glade', 'state': 'Florida'},
  {'city': 'Belle Haven', 'state': 'Virginia'},
  {'city': 'Bellefontaine', 'state': 'Ohio'},
  {'city': 'Bellefontaine Neighbors', 'state': 'Missouri'},
  {'city': 'Bellefonte', 'state': 'Pennsylvania'},
  {'city': 'Belleville', 'state': 'New Jersey'},
  {'city': 'Belleville', 'state': 'Illinois'},
  {'city': 'Bellevue', 'state': 'Kentucky'},
  {'city': 'Bellevue', 'state': 'Nebraska'},
  {'city': 'Bellevue', 'state': 'Ohio'},
  {'city': 'Bellevue', 'state': 'Pennsylvania'},
  {'city': 'Bellevue', 'state': 'Wisconsin'},
  {'city': 'Bellevue', 'state': 'Washington'},
  {'city': 'Bellevue Town', 'state': 'Wisconsin'},
  {'city': 'Bellflower', 'state': 'California'},
  {'city': 'Bellingham', 'state': 'Massachusetts'},
  {'city': 'Bellingham', 'state': 'Washington'},
  {'city': 'Bellmawr', 'state': 'New Jersey'},
  {'city': 'Bellmead', 'state': 'Texas'},
  {'city': 'Bellmore', 'state': 'New York'},
  {'city': 'Bellview', 'state': 'Florida'},
  {'city': 'Bellwood', 'state': 'Illinois'},
  {'city': 'Belmar', 'state': 'New Jersey'},
  {'city': 'Belmont', 'state': 'Massachusetts'},
  {'city': 'Belmont', 'state': 'New Hampshire'},
  {'city': 'Belmont', 'state': 'North Carolina'},
  {'city': 'Belmont', 'state': 'California'},
  {'city': 'Beloit', 'state': 'Wisconsin'},
  {'city': 'Belpre', 'state': 'Ohio'},
  {'city': 'Belton', 'state': 'Missouri'},
  {'city': 'Belton', 'state': 'Texas'},
  {'city': 'Beltsville', 'state': 'Maryland'},
  {'city': 'Belvedere Park', 'state': 'Georgia'},
  {'city': 'Belvidere', 'state': 'Illinois'},
  {'city': 'Bemidji', 'state': 'Minnesota'},
  {'city': 'Benbrook', 'state': 'Texas'},
  {'city': 'Bend', 'state': 'Oregon'},
  {'city': 'Benicia', 'state': 'California'},
  {'city': 'Bennettsville', 'state': 'South Carolina'},
  {'city': 'Bennington', 'state': 'Vermont'},
  {'city': 'Bennsville', 'state': 'Maryland'},
  {'city': 'Bensenville', 'state': 'Illinois'},
  {'city': 'Benton', 'state': 'Illinois'},
  {'city': 'Benton', 'state': 'Arkansas'},
  {'city': 'Benton Harbor', 'state': 'Michigan'},
  {'city': 'Bentonville', 'state': 'Arkansas'},
  {'city': 'Berea', 'state': 'Kentucky'},
  {'city': 'Berea', 'state': 'Ohio'},
  {'city': 'Berea', 'state': 'South Carolina'},
  {'city': 'Bergenfield', 'state': 'New Jersey'},
  {'city': 'Berkeley', 'state': 'Missouri'},
  {'city': 'Berkeley', 'state': 'California'},
  {'city': 'Berkeley Heights', 'state': 'New Jersey'},
  {'city': 'Berkley', 'state': 'Michigan'},
  {'city': 'Berkley', 'state': 'Colorado'},
  {'city': 'Berlin', 'state': 'Connecticut'},
  {'city': 'Berlin', 'state': 'New Jersey'},
  {'city': 'Berlin', 'state': 'New Hampshire'},
  {'city': 'Bermuda Dunes', 'state': 'California'},
  {'city': 'Bernalillo', 'state': 'New Mexico'},
  {'city': 'Bernardsville', 'state': 'New Jersey'},
  {'city': 'Berwick', 'state': 'Maine'},
  {'city': 'Berwick', 'state': 'Pennsylvania'},
  {'city': 'Berwyn', 'state': 'Illinois'},
  {'city': 'Bessemer', 'state': 'Alabama'},
  {'city': 'Bethalto', 'state': 'Illinois'},
  {'city': 'Bethany', 'state': 'Oklahoma'},
  {'city': 'Bethel', 'state': 'Connecticut'},
  {'city': 'Bethel Park', 'state': 'Pennsylvania'},
  {'city': 'Bethesda', 'state': 'Maryland'},
  {'city': 'Bethlehem', 'state': 'New York'},
  {'city': 'Bethlehem', 'state': 'Pennsylvania'},
  {'city': 'Bethpage', 'state': 'New York'},
  {'city': 'Bettendorf', 'state': 'Iowa'},
  {'city': 'Beverly', 'state': 'Massachusetts'},
  {'city': 'Beverly Hills', 'state': 'Michigan'},
  {'city': 'Beverly Hills', 'state': 'Florida'},
  {'city': 'Beverly Hills', 'state': 'California'},
  {'city': 'Bexley', 'state': 'Ohio'},
  {'city': 'Biddeford', 'state': 'Maine'},
  {'city': 'Big Flats', 'state': 'New York'},
  {'city': 'Big Lake', 'state': 'Minnesota'},
  {'city': 'Big Rapids', 'state': 'Michigan'},
  {'city': 'Big Spring', 'state': 'Texas'},
  {'city': 'Billerica', 'state': 'Massachusetts'},
  {'city': 'Billings', 'state': 'Montana'},
  {'city': 'Biloxi', 'state': 'Mississippi'},
  {'city': 'Binghamton', 'state': 'New York'},
  {'city': 'Birmingham', 'state': 'Michigan'},
  {'city': 'Birmingham', 'state': 'Alabama'},
  {'city': 'Bisbee', 'state': 'Arizona'},
  {'city': 'Bismarck', 'state': 'North Dakota'},
  {'city': 'Bixby', 'state': 'Oklahoma'},
  {'city': 'Black Forest', 'state': 'Colorado'},
  {'city': 'Black Jack', 'state': 'Missouri'},
  {'city': 'Black Mountain', 'state': 'North Carolina'},
  {'city': 'Blackfoot', 'state': 'Idaho'},
  {'city': 'Blackhawk-Camino Tassajara', 'state': 'California'},
  {'city': 'Blacklick Estates', 'state': 'Ohio'},
  {'city': 'Blacksburg', 'state': 'Virginia'},
  {'city': 'Blackstone', 'state': 'Massachusetts'},
  {'city': 'Blackwell', 'state': 'Oklahoma'},
  {'city': 'Bladensburg', 'state': 'Maryland'},
  {'city': 'Blaine', 'state': 'Minnesota'},
  {'city': 'Blair', 'state': 'Nebraska'},
  {'city': 'Blakely', 'state': 'Pennsylvania'},
  {'city': 'Bloomfield', 'state': 'New Jersey'},
  {'city': 'Bloomfield', 'state': 'New Mexico'},
  {'city': 'Bloomfield', 'state': 'Connecticut'},
  {'city': 'Bloomfield Township', 'state': 'Michigan'},
  {'city': 'Blooming Grove', 'state': 'New York'},
  {'city': 'Bloomingdale', 'state': 'New Jersey'},
  {'city': 'Bloomingdale', 'state': 'Florida'},
  {'city': 'Bloomingdale', 'state': 'Illinois'},
  {'city': 'Bloomingdale', 'state': 'Tennessee'},
  {'city': 'Bloomington', 'state': 'Illinois'},
  {'city': 'Bloomington', 'state': 'Indiana'},
  {'city': 'Bloomington', 'state': 'California'},
  {'city': 'Bloomington', 'state': 'Minnesota'},
  {'city': 'Bloomsburg', 'state': 'Pennsylvania'},
  {'city': 'Blue Ash', 'state': 'Ohio'},
  {'city': 'Blue Bell', 'state': 'Pennsylvania'},
  {'city': 'Blue Island', 'state': 'Illinois'},
  {'city': 'Blue Springs', 'state': 'Missouri'},
  {'city': 'Bluefield', 'state': 'West Virginia'},
  {'city': 'Bluffton', 'state': 'Indiana'},
  {'city': 'Blythe', 'state': 'California'},
  {'city': 'Blytheville', 'state': 'Arkansas'},
  {'city': 'Boardman', 'state': 'Ohio'},
  {'city': 'Boaz', 'state': 'Alabama'},
  {'city': 'Boca Del Mar', 'state': 'Florida'},
  {'city': 'Boca Raton', 'state': 'Florida'},
  {'city': 'Boerne', 'state': 'Texas'},
  {'city': 'Bogalusa', 'state': 'Louisiana'},
  {'city': 'Bogota', 'state': 'New Jersey'},
  {'city': 'Bohemia', 'state': 'New York'},
  {'city': 'Boise City', 'state': 'Idaho'},
  {'city': 'Bolingbrook', 'state': 'Illinois'},
  {'city': 'Bolivar', 'state': 'Missouri'},
  {'city': 'Bon Air', 'state': 'Virginia'},
  {'city': 'Bonadelle Ranchos-Madera Ranchos', 'state': 'California'},
  {'city': 'Bonham', 'state': 'Texas'},
  {'city': 'Bonita', 'state': 'California'},
  {'city': 'Bonita Springs', 'state': 'Florida'},
  {'city': 'Bonner Springs', 'state': 'Kansas'},
  {'city': 'Bonney Lake', 'state': 'Washington'},
  {'city': 'Boone', 'state': 'Iowa'},
  {'city': 'Boone', 'state': 'North Carolina'},
  {'city': 'Booneville', 'state': 'Mississippi'},
  {'city': 'Boonton', 'state': 'New Jersey'},
  {'city': 'Boonville', 'state': 'Missouri'},
  {'city': 'Boonville', 'state': 'Indiana'},
  {'city': 'Borger', 'state': 'Texas'},
  {'city': 'Bossier City', 'state': 'Louisiana'},
  {'city': 'Boston', 'state': 'Massachusetts'},
  {'city': 'Boston', 'state': 'New York'},
  {'city': 'Bostonia', 'state': 'California'},
  {'city': 'Bothell', 'state': 'Washington'},
  {'city': 'Boulder', 'state': 'Colorado'},
  {'city': 'Boulder City', 'state': 'Nevada'},
  {'city': 'Boulder Hill', 'state': 'Illinois'},
  {'city': 'Bound Brook', 'state': 'New Jersey'},
  {'city': 'Bountiful', 'state': 'Utah'},
  {'city': 'Bourbonnais', 'state': 'Illinois'},
  {'city': 'Bourne', 'state': 'Massachusetts'},
  {'city': 'Bow', 'state': 'New Hampshire'},
  {'city': 'Bowie', 'state': 'Maryland'},
  {'city': 'Bowleys Quarters', 'state': 'Maryland'},
  {'city': 'Bowling Green', 'state': 'Kentucky'},
  {'city': 'Bowling Green', 'state': 'Ohio'},
  {'city': 'Boxford', 'state': 'Massachusetts'},
  {'city': 'Boyes Hot Springs', 'state': 'California'},
  {'city': 'Boynton Beach', 'state': 'Florida'},
  {'city': 'Bozeman', 'state': 'Montana'},
  {'city': 'Bradenton', 'state': 'Florida'},
  {'city': 'Bradford', 'state': 'Pennsylvania'},
  {'city': 'Bradley', 'state': 'Illinois'},
  {'city': 'Brainerd', 'state': 'Minnesota'},
  {'city': 'Braintree', 'state': 'Massachusetts'},
  {'city': 'Brandon', 'state': 'Mississippi'},
  {'city': 'Brandon', 'state': 'Florida'},
  {'city': 'Branford', 'state': 'Connecticut'},
  {'city': 'Branson', 'state': 'Missouri'},
  {'city': 'Brattleboro', 'state': 'Vermont'},
  {'city': 'Brawley', 'state': 'California'},
  {'city': 'Brazil', 'state': 'Indiana'},
  {'city': 'Brea', 'state': 'California'},
  {'city': 'Breaux Bridge', 'state': 'Louisiana'},
  {'city': 'Brecksville', 'state': 'Ohio'},
  {'city': 'Bremerton', 'state': 'Washington'},
  {'city': 'Brenham', 'state': 'Texas'},
  {'city': 'Brent', 'state': 'Florida'},
  {'city': 'Brentwood', 'state': 'California'},
  {'city': 'Brentwood', 'state': 'New York'},
  {'city': 'Brentwood', 'state': 'Missouri'},
  {'city': 'Brentwood', 'state': 'Pennsylvania'},
  {'city': 'Brentwood', 'state': 'Tennessee'},
  {'city': 'Brevard', 'state': 'North Carolina'},
  {'city': 'Brewer', 'state': 'Maine'},
  {'city': 'Brewster', 'state': 'Massachusetts'},
  {'city': 'Briarcliff Manor', 'state': 'New York'},
  {'city': 'Bridge City', 'state': 'Louisiana'},
  {'city': 'Bridge City', 'state': 'Texas'},
  {'city': 'Bridgeport', 'state': 'West Virginia'},
  {'city': 'Bridgeport', 'state': 'Connecticut'},
  {'city': 'Bridgeport', 'state': 'Michigan'},
  {'city': 'Bridgeton', 'state': 'Missouri'},
  {'city': 'Bridgeton', 'state': 'New Jersey'},
  {'city': 'Bridgetown North', 'state': 'Ohio'},
  {'city': 'Bridgeview', 'state': 'Illinois'},
  {'city': 'Bridgewater', 'state': 'Massachusetts'},
  {'city': 'Brier', 'state': 'Washington'},
  {'city': 'Brigantine', 'state': 'New Jersey'},
  {'city': 'Brigham City', 'state': 'Utah'},
  {'city': 'Brighton', 'state': 'Michigan'},
  {'city': 'Brighton', 'state': 'New York'},
  {'city': 'Brighton', 'state': 'Colorado'},
  {'city': 'Bristol', 'state': 'Connecticut'},
  {'city': 'Bristol', 'state': 'Rhode Island'},
  {'city': 'Bristol', 'state': 'Tennessee'},
  {'city': 'Bristol', 'state': 'Virginia'},
  {'city': 'Bristol', 'state': 'Pennsylvania'},
  {'city': 'Broadview', 'state': 'Illinois'},
  {'city': 'Broadview Heights', 'state': 'Ohio'},
  {'city': 'Broadview Park', 'state': 'Florida'},
  {'city': 'Brockport', 'state': 'New York'},
  {'city': 'Brockton', 'state': 'Massachusetts'},
  {'city': 'Broken Arrow', 'state': 'Oklahoma'},
  {'city': 'Bronxville', 'state': 'New York'},
  {'city': 'Brook Park', 'state': 'Ohio'},
  {'city': 'Brookfield', 'state': 'Connecticut'},
  {'city': 'Brookfield', 'state': 'Illinois'},
  {'city': 'Brookfield', 'state': 'Wisconsin'},
  {'city': 'Brookhaven', 'state': 'Pennsylvania'},
  {'city': 'Brookhaven', 'state': 'New York'},
  {'city': 'Brookhaven', 'state': 'Mississippi'},
  {'city': 'Brookings', 'state': 'South Dakota'},
  {'city': 'Brookline', 'state': 'Massachusetts'},
  {'city': 'Brooklyn', 'state': 'Ohio'},
  {'city': 'Brooklyn', 'state': 'Connecticut'},
  {'city': 'Brooklyn Center', 'state': 'Minnesota'},
  {'city': 'Brooklyn Park', 'state': 'Minnesota'},
  {'city': 'Brooklyn Park', 'state': 'Maryland'},
  {'city': 'Brookside', 'state': 'Delaware'},
  {'city': 'Brooksville', 'state': 'Florida'},
  {'city': 'Broomall', 'state': 'Pennsylvania'},
  {'city': 'Broomfield', 'state': 'Colorado'},
  {'city': 'Brown Deer', 'state': 'Wisconsin'},
  {'city': 'Brownfield', 'state': 'Texas'},
  {'city': 'Browns Mills', 'state': 'New Jersey'},
  {'city': 'Brownsburg', 'state': 'Indiana'},
  {'city': 'Brownsville', 'state': 'Florida'},
  {'city': 'Brownsville', 'state': 'Texas'},
  {'city': 'Brownsville', 'state': 'Tennessee'},
  {'city': 'Brownsville-Bawcomville', 'state': 'Louisiana'},
  {'city': 'Brownwood', 'state': 'Texas'},
  {'city': 'Brunswick', 'state': 'Maine'},
  {'city': 'Brunswick', 'state': 'Georgia'},
  {'city': 'Brunswick', 'state': 'Ohio'},
  {'city': 'Brunswick', 'state': 'New York'},
  {'city': 'Brushy Creek', 'state': 'Texas'},
  {'city': 'Bryan', 'state': 'Texas'},
  {'city': 'Bryan', 'state': 'Ohio'},
  {'city': 'Bryant', 'state': 'Arkansas'},
  {'city': 'Bryn Mawr-Skyway', 'state': 'Washington'},
  {'city': 'Buckeye', 'state': 'Arizona'},
  {'city': 'Bucyrus', 'state': 'Ohio'},
  {'city': 'Budd Lake', 'state': 'New Jersey'},
  {'city': 'Buechel', 'state': 'Kentucky'},
  {'city': 'Buena Park', 'state': 'California'},
  {'city': 'Buena Vista', 'state': 'Michigan'},
  {'city': 'Buena Vista', 'state': 'Virginia'},
  {'city': 'Buffalo', 'state': 'Minnesota'},
  {'city': 'Buffalo', 'state': 'New York'},
  {'city': 'Buffalo Grove', 'state': 'Illinois'},
  {'city': 'Buford', 'state': 'Georgia'},
  {'city': 'Bull Run', 'state': 'Virginia'},
  {'city': 'Bullhead City', 'state': 'Arizona'},
  {'city': 'Burbank', 'state': 'California'},
  {'city': 'Burbank', 'state': 'Illinois'},
  {'city': 'Burien', 'state': 'Washington'},
  {'city': 'Burkburnett', 'state': 'Texas'},
  {'city': 'Burke', 'state': 'Virginia'},
  {'city': 'Burleson', 'state': 'Texas'},
  {'city': 'Burley', 'state': 'Idaho'},
  {'city': 'Burlingame', 'state': 'California'},
  {'city': 'Burlington', 'state': 'Connecticut'},
  {'city': 'Burlington', 'state': 'Kentucky'},
  {'city': 'Burlington', 'state': 'Iowa'},
  {'city': 'Burlington', 'state': 'North Carolina'},
  {'city': 'Burlington', 'state': 'Massachusetts'},
  {'city': 'Burlington', 'state': 'New Jersey'},
  {'city': 'Burlington', 'state': 'Vermont'},
  {'city': 'Burlington', 'state': 'Washington'},
  {'city': 'Burlington', 'state': 'Wisconsin'},
  {'city': 'Burnsville', 'state': 'Minnesota'},
  {'city': 'Burr Ridge', 'state': 'Illinois'},
  {'city': 'Burrillville', 'state': 'Rhode Island'},
  {'city': 'Burton', 'state': 'South Carolina'},
  {'city': 'Burton', 'state': 'Michigan'},
  {'city': 'Burtonsville', 'state': 'Maryland'},
  {'city': 'Busti', 'state': 'New York'},
  {'city': 'Butler', 'state': 'New Jersey'},
  {'city': 'Butler', 'state': 'Pennsylvania'},
  {'city': 'Butte-Silver Bow', 'state': 'Montana'},
  {'city': 'Buxton', 'state': 'Maine'},
  {'city': 'Byram', 'state': 'Mississippi'},

  {'city': 'Cabot', 'state': 'Arkansas'},
  {'city': 'Cadillac', 'state': 'Michigan'},
  {'city': 'Cahokia', 'state': 'Illinois'},
  {'city': 'Cairo', 'state': 'Georgia'},
  {'city': 'Cairo', 'state': 'New York'},
  {'city': 'Calabasas', 'state': 'California'},
  {'city': 'Caldwell', 'state': 'New Jersey'},
  {'city': 'Caldwell', 'state': 'Idaho'},
  {'city': 'Caledonia', 'state': 'Wisconsin'},
  {'city': 'Calexico', 'state': 'California'},
  {'city': 'Calhoun', 'state': 'Georgia'},
  {'city': 'California', 'state': 'Maryland'},
  {'city': 'California City', 'state': 'California'},
  {'city': 'Calimesa', 'state': 'California'},
  {'city': 'Calipatria', 'state': 'California'},
  {'city': 'Callaway', 'state': 'Florida'},
  {'city': 'Calumet City', 'state': 'Illinois'},
  {'city': 'Calumet Park', 'state': 'Illinois'},
  {'city': 'Calverton', 'state': 'Maryland'},
  {'city': 'Camano', 'state': 'Washington'},
  {'city': 'Camarillo', 'state': 'California'},
  {'city': 'Camas', 'state': 'Washington'},
  {'city': 'Cambria', 'state': 'California'},
  {'city': 'Cambridge', 'state': 'Maryland'},
  {'city': 'Cambridge', 'state': 'Massachusetts'},
  {'city': 'Cambridge', 'state': 'Ohio'},
  {'city': 'Camden', 'state': 'South Carolina'},
  {'city': 'Camden', 'state': 'New Jersey'},
  {'city': 'Camden', 'state': 'Arkansas'},
  {'city': 'Cameron', 'state': 'Missouri'},
  {'city': 'Cameron Park', 'state': 'California'},
  {'city': 'Camillus', 'state': 'New York'},
  {'city': 'Camp Hill', 'state': 'Pennsylvania'},
  {'city': 'Camp Pendleton North', 'state': 'California'},
  {'city': 'Camp Pendleton South', 'state': 'California'},
  {'city': 'Camp Springs', 'state': 'Maryland'},
  {'city': 'Camp Verde', 'state': 'Arizona'},
  {'city': 'Campbell', 'state': 'California'},
  {'city': 'Campbell', 'state': 'Ohio'},
  {'city': 'Campbellsville', 'state': 'Kentucky'},
  {'city': 'Canandaigua', 'state': 'New York'},
  {'city': 'Canby', 'state': 'Oregon'},
  {'city': 'Candler-McAfee', 'state': 'Georgia'},
  {'city': 'Canfield', 'state': 'Ohio'},
  {'city': 'Canon City', 'state': 'Colorado'},
  {'city': 'Canonsburg', 'state': 'Pennsylvania'},
  {'city': 'Canton', 'state': 'Ohio'},
  {'city': 'Canton', 'state': 'Georgia'},
  {'city': 'Canton', 'state': 'Illinois'},
  {'city': 'Canton', 'state': 'Connecticut'},
  {'city': 'Canton', 'state': 'New York'},
  {'city': 'Canton', 'state': 'Mississippi'},
  {'city': 'Canton', 'state': 'Massachusetts'},
  {'city': 'Canton', 'state': 'Michigan'},
  {'city': 'Canyon', 'state': 'Texas'},
  {'city': 'Canyon Lake', 'state': 'Texas'},
  {'city': 'Canyon Lake', 'state': 'California'},
  {'city': 'Canyon Rim', 'state': 'Utah'},
  {'city': 'Cape Canaveral', 'state': 'Florida'},
  {'city': 'Cape Coral', 'state': 'Florida'},
  {'city': 'Cape Elizabeth', 'state': 'Maine'},
  {'city': 'Cape Girardeau', 'state': 'Missouri'},
  {'city': 'Cape St. Claire', 'state': 'Maryland'},
  {'city': 'Capitola', 'state': 'California'},
  {'city': 'Carbondale', 'state': 'Illinois'},
  {'city': 'Carbondale', 'state': 'Pennsylvania'},
  {'city': 'Carencro', 'state': 'Louisiana'},
  {'city': 'Caribou', 'state': 'Maine'},
  {'city': 'Carlisle', 'state': 'Pennsylvania'},
  {'city': 'Carlsbad', 'state': 'New Mexico'},
  {'city': 'Carlsbad', 'state': 'California'},
  {'city': 'Carmel', 'state': 'Indiana'},
  {'city': 'Carmel', 'state': 'New York'},
  {'city': 'Carmichael', 'state': 'California'},
  {'city': 'Carnegie', 'state': 'Pennsylvania'},
  {'city': 'Carney', 'state': 'Maryland'},
  {'city': 'Carneys Point', 'state': 'New Jersey'},
  {'city': 'Carnot-Moon', 'state': 'Pennsylvania'},
  {'city': 'Carol City', 'state': 'Florida'},
  {'city': 'Carol Stream', 'state': 'Illinois'},
  {'city': 'Carpentersville', 'state': 'Illinois'},
  {'city': 'Carpinteria', 'state': 'California'},
  {'city': 'Carrboro', 'state': 'North Carolina'},
  {'city': 'Carroll', 'state': 'Iowa'},
  {'city': 'Carrollton', 'state': 'Michigan'},
  {'city': 'Carrollton', 'state': 'Georgia'},
  {'city': 'Carrollton', 'state': 'Texas'},
  {'city': 'Carson', 'state': 'California'},
  {'city': 'Carson City', 'state': 'Nevada'},
  {'city': 'Carteret', 'state': 'New Jersey'},
  {'city': 'Cartersville', 'state': 'Georgia'},
  {'city': 'Carthage', 'state': 'Missouri'},
  {'city': 'Carthage', 'state': 'Texas'},
  {'city': 'Caruthersville', 'state': 'Missouri'},
  {'city': 'Carver', 'state': 'Massachusetts'},
  {'city': 'Cary', 'state': 'Illinois'},
  {'city': 'Cary', 'state': 'North Carolina'},
  {'city': 'Casa de Oro-Mount Helix', 'state': 'California'},
  {'city': 'Casa Grande', 'state': 'Arizona'},
  {'city': 'Casas Adobes', 'state': 'Arizona'},
  {'city': 'Cascade-Fairwood', 'state': 'Washington'},
  {'city': 'Casper', 'state': 'Wyoming'},
  {'city': 'Casselberry', 'state': 'Florida'},
  {'city': 'Castle Rock', 'state': 'Colorado'},
  {'city': 'Castle Shannon', 'state': 'Pennsylvania'},
  {'city': 'Castlewood', 'state': 'Colorado'},
  {'city': 'Castro Valley', 'state': 'California'},
  {'city': 'Castroville', 'state': 'California'},
  {'city': 'Catalina', 'state': 'Arizona'},
  {'city': 'Catalina Foothills', 'state': 'Arizona'},
  {'city': 'Catasauqua', 'state': 'Pennsylvania'},
  {'city': 'Cathedral City', 'state': 'California'},
  {'city': 'Catonsville', 'state': 'Maryland'},
  {'city': 'Catskill', 'state': 'New York'},
  {'city': 'Cave Spring', 'state': 'Virginia'},
  {'city': 'Cayce', 'state': 'South Carolina'},
  {'city': 'Cazenovia', 'state': 'New York'},
  {'city': 'Cedar City', 'state': 'Utah'},
  {'city': 'Cedar Falls', 'state': 'Iowa'},
  {'city': 'Cedar Grove', 'state': 'New Jersey'},
  {'city': 'Cedar Hill', 'state': 'Texas'},
  {'city': 'Cedar Hills', 'state': 'Oregon'},
  {'city': 'Cedar Lake', 'state': 'Indiana'},
  {'city': 'Cedar Mill', 'state': 'Oregon'},
  {'city': 'Cedar Park', 'state': 'Texas'},
  {'city': 'Cedar Rapids', 'state': 'Iowa'},
  {'city': 'Cedarburg', 'state': 'Wisconsin'},
  {'city': 'Cedarhurst', 'state': 'New York'},
  {'city': 'Cedartown', 'state': 'Georgia'},
  {'city': 'Celina', 'state': 'Ohio'},
  {'city': 'Center Line', 'state': 'Michigan'},
  {'city': 'Center Moriches', 'state': 'New York'},
  {'city': 'Center Point', 'state': 'Alabama'},
  {'city': 'Centereach', 'state': 'New York'},
  {'city': 'Centerville', 'state': 'Ohio'},
  {'city': 'Centerville', 'state': 'Utah'},
  {'city': 'Central Falls', 'state': 'Rhode Island'},
  {'city': 'Central Islip', 'state': 'New York'},
  {'city': 'Central Manchester', 'state': 'Connecticut'},
  {'city': 'Central Point', 'state': 'Oregon'},
  {'city': 'Centralia', 'state': 'Washington'},
  {'city': 'Centralia', 'state': 'Illinois'},
  {'city': 'Centreville', 'state': 'Virginia'},
  {'city': 'Century Village', 'state': 'Florida'},
  {'city': 'Ceres', 'state': 'California'},
  {'city': 'Cerritos', 'state': 'California'},
  {'city': 'Chalco', 'state': 'Nebraska'},
  {'city': 'Chalmette', 'state': 'Louisiana'},
  {'city': 'Chambersburg', 'state': 'Pennsylvania'},
  {'city': 'Chamblee', 'state': 'Georgia'},
  {'city': 'Champaign', 'state': 'Illinois'},
  {'city': 'Champlin', 'state': 'Minnesota'},
  {'city': 'Chandler', 'state': 'Arizona'},
  {'city': 'Chanhassen', 'state': 'Minnesota'},
  {'city': 'Channahon', 'state': 'Illinois'},
  {'city': 'Channelview', 'state': 'Texas'},
  {'city': 'Chantilly', 'state': 'Virginia'},
  {'city': 'Chanute', 'state': 'Kansas'},
  {'city': 'Chaparral', 'state': 'New Mexico'},
  {'city': 'Chapel Hill', 'state': 'North Carolina'},
  {'city': 'Chappaqua', 'state': 'New York'},
  {'city': 'Charles City', 'state': 'Iowa'},
  {'city': 'Charleston', 'state': 'Illinois'},
  {'city': 'Charleston', 'state': 'West Virginia'},
  {'city': 'Charleston', 'state': 'South Carolina'},
  {'city': 'Charlestown', 'state': 'Rhode Island'},
  {'city': 'Charlotte', 'state': 'North Carolina'},
  {'city': 'Charlotte', 'state': 'Michigan'},
  {'city': 'Charlottesville', 'state': 'Virginia'},
  {'city': 'Charlton', 'state': 'Massachusetts'},
  {'city': 'Charter Oak', 'state': 'California'},
  {'city': 'Chaska', 'state': 'Minnesota'},
  {'city': 'Chatham', 'state': 'Massachusetts'},
  {'city': 'Chatham', 'state': 'New Jersey'},
  {'city': 'Chatham', 'state': 'Illinois'},
  {'city': 'Chattanooga', 'state': 'Tennessee'},
  {'city': 'Cheat Lake', 'state': 'West Virginia'},
  {'city': 'Cheektowaga', 'state': 'New York'},
  {'city': 'Chehalis', 'state': 'Washington'},
  {'city': 'Chelmsford', 'state': 'Massachusetts'},
  {'city': 'Chelsea', 'state': 'Massachusetts'},
  {'city': 'Chenango', 'state': 'New York'},
  {'city': 'Cheney', 'state': 'Washington'},
  {'city': 'Cherry Hill Mall', 'state': 'New Jersey'},
  {'city': 'Cherryland', 'state': 'California'},
  {'city': 'Chesapeake', 'state': 'Virginia'},
  {'city': 'Chesapeake Ranch Estates-Drum Point', 'state': 'Maryland'},
  {'city': 'Cheshire', 'state': 'Connecticut'},
  {'city': 'Chester', 'state': 'New York'},
  {'city': 'Chester', 'state': 'Virginia'},
  {'city': 'Chester', 'state': 'South Carolina'},
  {'city': 'Chester', 'state': 'Pennsylvania'},
  {'city': 'Chesterfield', 'state': 'Missouri'},
  {'city': 'Chesterton', 'state': 'Indiana'},
  {'city': 'Chestnut Ridge', 'state': 'New York'},
  {'city': 'Cheval', 'state': 'Florida'},
  {'city': 'Cheverly', 'state': 'Maryland'},
  {'city': 'Cheviot', 'state': 'Ohio'},
  {'city': 'Chevy Chase', 'state': 'Maryland'},
  {'city': 'Cheyenne', 'state': 'Wyoming'},
  {'city': 'Chicago', 'state': 'Illinois'},
  {'city': 'Chicago Heights', 'state': 'Illinois'},
  {'city': 'Chicago Ridge', 'state': 'Illinois'},
  {'city': 'Chickasaw', 'state': 'Alabama'},
  {'city': 'Chickasha', 'state': 'Oklahoma'},
  {'city': 'Chico', 'state': 'California'},
  {'city': 'Chicopee', 'state': 'Massachusetts'},
  {'city': 'Childress', 'state': 'Texas'},
  {'city': 'Chili', 'state': 'New York'},
  {'city': 'Chillicothe', 'state': 'Missouri'},
  {'city': 'Chillicothe', 'state': 'Ohio'},
  {'city': 'Chillum', 'state': 'Maryland'},
  {'city': 'Chino', 'state': 'California'},
  {'city': 'Chino Hills', 'state': 'California'},
  {'city': 'Chino Valley', 'state': 'Arizona'},
  {'city': 'Chippewa Falls', 'state': 'Wisconsin'},
  {'city': 'Choctaw', 'state': 'Oklahoma'},
  {'city': 'Chowchilla', 'state': 'California'},
  {'city': 'Christiansburg', 'state': 'Virginia'},
  {'city': 'Chubbuck', 'state': 'Idaho'},
  {'city': 'Chula Vista', 'state': 'California'},
  {'city': 'Cicero', 'state': 'Illinois'},
  {'city': 'Cicero', 'state': 'New York'},
  {'city': 'Cimarron Hills', 'state': 'Colorado'},
  {'city': 'Cincinnati', 'state': 'Ohio'},
  {'city': 'Cinco Ranch', 'state': 'Texas'},
  {'city': 'Circleville', 'state': 'Ohio'},
  {'city': 'Citrus', 'state': 'California'},
  {'city': 'Citrus Heights', 'state': 'California'},
  {'city': 'Citrus Park', 'state': 'Florida'},
  {'city': 'Citrus Ridge', 'state': 'Florida'},
  {'city': 'City of The Dalles', 'state': 'Oregon'},
  {'city': 'Claiborne', 'state': 'Louisiana'},
  {'city': 'Clairton', 'state': 'Pennsylvania'},
  {'city': 'Clanton', 'state': 'Alabama'},
  {'city': 'Claremont', 'state': 'California'},
  {'city': 'Claremont', 'state': 'New Hampshire'},
  {'city': 'Claremore', 'state': 'Oklahoma'},
  {'city': 'Clarence', 'state': 'New York'},
  {'city': 'Clarendon Hills', 'state': 'Illinois'},
  {'city': 'Clarion', 'state': 'Pennsylvania'},
  {'city': 'Clark', 'state': 'New Jersey'},
  {'city': 'Clarksburg', 'state': 'West Virginia'},
  {'city': 'Clarksdale', 'state': 'Mississippi'},
  {'city': 'Clarkson', 'state': 'New York'},
  {'city': 'Clarkston', 'state': 'Georgia'},
  {'city': 'Clarkston', 'state': 'Washington'},
  {'city': 'Clarkston Heights-Vineland', 'state': 'Washington'},
  {'city': 'Clarkstown', 'state': 'New York'},
  {'city': 'Clarksville', 'state': 'Indiana'},
  {'city': 'Clarksville', 'state': 'Arkansas'},
  {'city': 'Clarksville', 'state': 'Tennessee'},
  {'city': 'Claverack', 'state': 'New York'},
  {'city': 'Clawson', 'state': 'Michigan'},
  {'city': 'Clay', 'state': 'New York'},
  {'city': 'Claymont', 'state': 'Delaware'},
  {'city': 'Clayton', 'state': 'California'},
  {'city': 'Clayton', 'state': 'Missouri'},
  {'city': 'Clayton', 'state': 'New Jersey'},
  {'city': 'Clayton', 'state': 'Ohio'},
  {'city': 'Clayton', 'state': 'North Carolina'},
  {'city': 'Clear Lake', 'state': 'Iowa'},
  {'city': 'Clearfield', 'state': 'Pennsylvania'},
  {'city': 'Clearfield', 'state': 'Utah'},
  {'city': 'Clearlake', 'state': 'California'},
  {'city': 'Clearwater', 'state': 'Florida'},
  {'city': 'Cleburne', 'state': 'Texas'},
  {'city': 'Clemmons', 'state': 'North Carolina'},
  {'city': 'Clemson', 'state': 'South Carolina'},
  {'city': 'Clermont', 'state': 'Florida'},
  {'city': 'Cleveland', 'state': 'Mississippi'},
  {'city': 'Cleveland', 'state': 'Tennessee'},
  {'city': 'Cleveland', 'state': 'Texas'},
  {'city': 'Cleveland', 'state': 'Ohio'},
  {'city': 'Cleveland Heights', 'state': 'Ohio'},
  {'city': 'Clewiston', 'state': 'Florida'},
  {'city': 'Cliffside Park', 'state': 'New Jersey'},
  {'city': 'Clifton', 'state': 'New Jersey'},
  {'city': 'Clifton', 'state': 'Colorado'},
  {'city': 'Clifton Heights', 'state': 'Pennsylvania'},
  {'city': 'Clifton Park', 'state': 'New York'},
  {'city': 'Clinton', 'state': 'Mississippi'},
  {'city': 'Clinton', 'state': 'Missouri'},
  {'city': 'Clinton', 'state': 'Iowa'},
  {'city': 'Clinton', 'state': 'Maryland'},
  {'city': 'Clinton', 'state': 'Michigan'},
  {'city': 'Clinton', 'state': 'Massachusetts'},
  {'city': 'Clinton', 'state': 'Connecticut'},
  {'city': 'Clinton', 'state': 'Illinois'},
  {'city': 'Clinton', 'state': 'Oklahoma'},
  {'city': 'Clinton', 'state': 'North Carolina'},
  {'city': 'Clinton', 'state': 'Tennessee'},
  {'city': 'Clinton', 'state': 'South Carolina'},
  {'city': 'Clinton', 'state': 'Utah'},
  {'city': 'Clive', 'state': 'Iowa'},
  {'city': 'Cloquet', 'state': 'Minnesota'},
  {'city': 'Closter', 'state': 'New Jersey'},
  {'city': 'Cloverdale', 'state': 'California'},
  {'city': 'Cloverleaf', 'state': 'Texas'},
  {'city': 'Cloverly', 'state': 'Maryland'},
  {'city': 'Clovis', 'state': 'New Mexico'},
 ];

export default data;
